### ISSUE TITLE
Signing documents with an Estonian ID

### ISSUE THREAD

**Issue by notpushkin** [MatthiasValvekens/pyHanko#38]
Thanks for such a useful little tool! I'm trying to utilize it to sign a PDF using my Estonian ID card. So far by trial and error, I've managed to get to this command:

```sh
pyhanko sign addsig pkcs11 \
  --lib /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so \
  --token-label 'PUSHKOV,ALEKSANDR,3970... (PIN2)' \
  --cert-label 'Allkirjastamine' \
  test.pdf signed.pdf
```

But it fails with the `pkcs11.exceptions.MechanismInvalid` error.

<details><summary>Full output</summary>
```
PKCS#11 user PIN: 
2021-09-27 18:33:09,048 - pyhanko.cli - ERROR - Generic processing error.
Traceback (most recent call last):
  File "/home/ale/.local/pipx/venvs/pyHanko/lib/python3.8/site-packages/pyhanko/cli.py", line 75, in pyhanko_exception_manager
    yield
  File "/home/ale/.local/pipx/venvs/pyHanko/lib/python3.8/site-packages/pyhanko/cli.py", line 981, in _sign_pkcs11
    generic_sign_pdf(
  File "/home/ale/.local/pipx/venvs/pyHanko/lib/python3.8/site-packages/pyhanko/cli.py", line 795, in generic_sign_pdf
    result = signers.PdfSigner(
  File "/home/ale/.local/pipx/venvs/pyHanko/lib/python3.8/site-packages/pyhanko/sign/signers/pdf_signer.py", line 990, in sign_pdf
    post_signing_doc = tbs_document.perform_signature(
  File "/home/ale/.local/pipx/venvs/pyHanko/lib/python3.8/site-packages/pyhanko/sign/signers/pdf_signer.py", line 1687, in perform_signature
    signature_cms = self.signer.sign(
  File "/home/ale/.local/pipx/venvs/pyHanko/lib/python3.8/site-packages/pyhanko/sign/signers/pdf_cms.py", line 465, in sign
    return self.sign_prescribed_attributes(
  File "/home/ale/.local/pipx/venvs/pyHanko/lib/python3.8/site-packages/pyhanko/sign/signers/pdf_cms.py", line 538, in sign_prescribed_attributes
    signature = self.sign_raw(
  File "/home/ale/.local/pipx/venvs/pyHanko/lib/python3.8/site-packages/pyhanko/sign/pkcs11.py", line 266, in sign_raw
    signature = kh.sign(data, **kwargs)
  File "/home/ale/.local/pipx/venvs/pyHanko/lib/python3.8/site-packages/pkcs11/types.py", line 939, in sign
    return self._sign(data, **kwargs)
  File "pkcs11/_pkcs11.pyx", line 1072, in pkcs11._pkcs11.SignMixin._sign
  File "pkcs11/_pkcs11.pyx", line 1074, in pkcs11._pkcs11.SignMixin._sign
  File "pkcs11/_errors.pyx", line 88, in pkcs11._pkcs11.assertRV
pkcs11.exceptions.MechanismInvalid
Error: Generic processing error.
```
</details>

I've added a couple quick `print`s to `pyhanko.sign.pkcs11.PKCS11Signer.sing_raw` to verify that the mechanism picked is indeed correct and it seems plausible to me:

```
signature_algo: ecdsa
digest_algorithm: sha256
```

Here's some info about the certificate and the card itself:

```
$ pkcs11-tool --slot 1 -OM
Supported mechanisms:
  SHA-1, digest
  SHA224, digest
  SHA256, digest
  SHA384, digest
  SHA512, digest
  MD5, digest
  RIPEMD160, digest
  GOSTR3411, digest
  ECDSA, keySize={384,384}, hw, sign, other flags=0x1800000
  ECDH1-COFACTOR-DERIVE, keySize={384,384}, hw, derive, other flags=0x1800000
  ECDH1-DERIVE, keySize={384,384}, hw, derive, other flags=0x1800000
Certificate Object; type = X.509 cert
  label:      Allkirjastamine
  subject:    DN: C=EE, O=ESTEID, OU=digital signature, CN=PUSHKOV,ALEKSANDR,397xxxxxxxx, SN=PUSHKOV, GN=ALEKSANDR/serialNumber=397xxxxxxxx
  ID:         02
Public Key Object; EC  EC_POINT 384 bits
  EC_POINT:   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  EC_PARAMS:  06052b81040022
  label:      Allkirjastamine
  ID:         02
  Usage:      encrypt, verify
  Access:     local
```

What are my next steps to solve this mystery? :-)

**Comment by MatthiasValvekens** [comment]
Thanks for the detailed issue report!

Hmmm, at first sight, it could be either of two things:

 - You have to use ECDSA-with-SHA384 (as opposed to ECDSA-with-SHA256, which is what you're using now).
 - Your token only supports ECDSA in "raw" mode.

It looks like it's the latter, but you can try if option 1 works by setting the digest function to SHA384 in the `PdfSignatureMetadata` object.

If your device only does "raw" ECDSA, then there's a bit of an issue: my PKCS#11 signer doesn't handle that right now. I'd have to look up the precise semantics, but it should be possible to make that work as well, by passing in pre-hashed data. Let me look into that and get back to you later.

-----

I'll mark this as "enhancement" because it boils down to either having to implement raw ECDSA support in the PKCS#11 signer, or because pyHanko hard-defaults to SHA256 if the digest function is unknown, instead of trying to intelligently guess a digest method based on key sizes (or something of that nature).
