### ISSUE TITLE
verify https://autenti.com/ signed pdf by pyhanko 

### ISSUE THREAD

**Issue by areqq** [MatthiasValvekens/pyHanko#55]
pyHanko-0.9.0 on linux Python 3.7.3

pdf signed on https://autenti.com/
after
```
./.local/bin/pyhanko sign validate --pretty-print PDF_sign_test.pdf
```
I got:
```
2021-11-13 20:09:13,402 - pyhanko.sign.diff_analysis - WARNING - Error in diff operation between revision 1 and 5
Traceback (most recent call last):
  File "/home/eod/.local/lib/python3.7/site-packages/pyhanko/sign/diff_analysis.py", line 2240, in review_file
    field_mdp_spec=field_mdp_spec, doc_mdp=doc_mdp
  File "/home/eod/.local/lib/python3.7/site-packages/pyhanko/sign/diff_analysis.py", line 2131, in apply
    for level, fu in form_changes:
  File "/home/eod/.local/lib/python3.7/site-packages/pyhanko/sign/diff_analysis.py", line 1304, in apply
    yield from rule.apply(context)
  File "/home/eod/.local/lib/python3.7/site-packages/pyhanko/sign/diff_analysis.py", line 981, in apply
    yield from self.check_form_field(fq_name, spec, context)
  File "/home/eod/.local/lib/python3.7/site-packages/pyhanko/sign/diff_analysis.py", line 1046, in check_form_field
    valid_when_locked = self.compare_fields(spec)
  File "/home/eod/.local/lib/python3.7/site-packages/pyhanko/sign/diff_analysis.py", line 971, in compare_fields
    old_field, new_field, self.value_update_keys
  File "/home/eod/.local/lib/python3.7/site-packages/pyhanko/sign/diff_analysis.py", line 1806, in _compare_dicts
    f"Dict keys differ: {new_dict_keys} vs. "
pyhanko.sign.diff_analysis.SuspiciousModification: Dict keys differ: {'/Lock', '/P', '/Rect', '/FT', '/Subtype', '/T'} vs. {'/P', '/Rect', '/FT', '/Subtype', '/T'}.
2021-11-13 20:09:13,412 - pyhanko.sign.general - WARNING - Unable to build a validation path for the certificate "Organization Identifier: VATPL-5170359458, Common Name: Certum QTST 2017, Organization: Asseco Data Systems S.A., Country: PL" - no issuer matching "Organization Identifier: VATPL-5250008198, Common Name: Narodowe Centrum Certyfikacji, Organization: Narodowy Bank Polski, Country: PL" was found
2021-11-13 20:09:13,412 - pyhanko.sign.general - WARNING - Chain of trust validation for Organization Identifier: VATPL-5170359458, Common Name: Certum QTST 2017, Organization: Asseco Data Systems S.A., Country: PL failed.
2021-11-13 20:09:13,436 - pyhanko.cli - ERROR - Generic processing error.
Traceback (most recent call last):
  File "/home/eod/.local/lib/python3.7/site-packages/pyhanko_certvalidator/fetchers/common_utils.py", line 139, in queue_fetch_task
    wait_event: asyncio.Event = running_jobs[tag]
KeyError: 'http://elektronicznypodpis.pl/certyfikaty/ozk62.der'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eod/.local/lib/python3.7/site-packages/pyhanko/cli.py", line 80, in pyhanko_exception_manager
    yield
  File "/home/eod/.local/lib/python3.7/site-packages/pyhanko/cli.py", line 518, in validate_signatures
    pretty_print=pretty_print, executive_summary=executive_summary
  File "/home/eod/.local/lib/python3.7/site-packages/pyhanko/cli.py", line 386, in _signature_status_str
    status = status_callback()
  File "/home/eod/.local/lib/python3.7/site-packages/pyhanko/cli.py", line 516, in <lambda>
    embedded_sig=embedded_sig
  File "/home/eod/.local/lib/python3.7/site-packages/pyhanko/cli.py", line 352, in _signature_status
    signer_validation_context=vc
  File "/home/eod/.local/lib/python3.7/site-packages/pyhanko/sign/validation.py", line 1569, in validate_pdf_signature
    return asyncio.run(coro)
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/eod/.local/lib/python3.7/site-packages/pyhanko/sign/validation.py", line 1639, in async_validate_pdf_signature
    status_kwargs=status_kwargs, key_usage_settings=key_usage_settings
  File "/home/eod/.local/lib/python3.7/site-packages/pyhanko/sign/validation.py", line 266, in _validate_cms_signature
    validator, key_usage_settings=key_usage_settings
  File "/home/eod/.local/lib/python3.7/site-packages/pyhanko/sign/general.py", line 373, in validate_cert_usage
    path = await validator.async_validate_usage(key_usage=set())
  File "/home/eod/.local/lib/python3.7/site-packages/pyhanko_certvalidator/__init__.py", line 283, in async_validate_usage
    await self._validate_path()
  File "/home/eod/.local/lib/python3.7/site-packages/pyhanko_certvalidator/__init__.py", line 128, in _validate_path
    self._certificate
  File "/home/eod/.local/lib/python3.7/site-packages/pyhanko_certvalidator/registry.py", line 426, in async_build_paths
    await self._walk_issuers(path, paths, failed_paths)
  File "/home/eod/.local/lib/python3.7/site-packages/pyhanko_certvalidator/registry.py", line 478, in _walk_issuers
    async for issuer in self.fetcher.fetch_cert_issuers(path.first):
  File "/home/eod/.local/lib/python3.7/site-packages/pyhanko_certvalidator/fetchers/requests_fetchers/cert_fetch_client.py", line 70, in fetch_cert_issuers
    url, url_origin_type='certificate'
  File "/home/eod/.local/lib/python3.7/site-packages/pyhanko_certvalidator/fetchers/requests_fetchers/cert_fetch_client.py", line 56, in fetch_certs
    return await self._perform_fetch(url, task)
  File "/home/eod/.local/lib/python3.7/site-packages/pyhanko_certvalidator/fetchers/requests_fetchers/util.py", line 38, in _perform_fetch
    self.__results, self.__result_events, tag, fetch_fun
  File "/home/eod/.local/lib/python3.7/site-packages/pyhanko_certvalidator/fetchers/common_utils.py", line 170, in queue_fetch_task
    return _return_or_raise(result)
  File "/home/eod/.local/lib/python3.7/site-packages/pyhanko_certvalidator/fetchers/common_utils.py", line 175, in _return_or_raise
    raise result
  File "/home/eod/.local/lib/python3.7/site-packages/pyhanko_certvalidator/fetchers/common_utils.py", line 157, in queue_fetch_task
    result = await async_fun()
  File "/home/eod/.local/lib/python3.7/site-packages/pyhanko_certvalidator/fetchers/requests_fetchers/cert_fetch_client.py", line 55, in task
    return list(results)
  File "/home/eod/.local/lib/python3.7/site-packages/pyhanko_certvalidator/fetchers/common_utils.py", line 46, in unpack_cert_content
    "Expected PEM data when extracting certs from "
ValueError: Expected PEM data when extracting certs from application/x-x509-ca-cert payload. Source URL: http://elektronicznypodpis.pl/certyfikaty/ozk62.der.
Error: Generic processing error.
```

what I did wrong ?

[PDF_sign_test.pdf](https://github.com/MatthiasValvekens/pyHanko/files/7532605/PDF_sign_test.pdf)
?

**Comment by MatthiasValvekens** [comment]
Hi, thanks for checking in!

So, there are two things happening here:

 - pyHanko is complaining about a field lock dictionary that got added to an existing signature field. This is a matter of interpretation, I'll explain below.
 - When downloading the certificate at  http://elektronicznypodpis.pl/certyfikaty/ozk62.der, the certificate fetcher expected to receive PEM data, but it actually received a DER-encoded certificate, and threw an error. Judging from the comments in the code, this seems to be a bug in [pyhanko-certvalidator](https://github.com/MatthiasValvekens/certvalidator).

First things first: the certificate fetching bug is fairly easy to fix, but in the meantime, you can work around it by manually downloading the certificate from 'http://elektronicznypodpis.pl/certyfikaty/ozk62.der' and passing it as an untrusted relevant certificate using the `--other-certs` option of the `validate` subcommand. You might also have to pass [this trust root](https://www.nccert.pl/files/nccert2016.crt) using the `--trust` flag for that to work, unless you have all the relevant Polish trust roots available in your system trust already---they weren't present on my system, for example.

The issue with the `SuspiciousModification` error is more delicate. PyHanko is one of the few OSS PDF signing toolkits to implement incremental update analysis, and it takes a fairly conservative stance by default. Messing with form properties on existing form fields is something it does not look kindly upon. Arguably, the implementer of the signing service at autenti.com should have put a field lock dictionary in place when it created the `FinalizingSeal` field, not after applying all the other signatures. But this area of PDF signature validation is very poorly standardised, so it's hard to fault either side here.
It's possible to customise pyHanko's difference analysis procedure, but not from the CLI, unfortunately. I should perhaps add a CLI flag to suppress difference analysis.

Hopefully that answers some of your questions.

**Comment by MatthiasValvekens** [comment]
I added a `--no-diff-analysis` CLI flag to skip the difference analysis (since there are other issues besides the one you highlighted). I also fixed the certificate fetching bug in `pyhanko-certvalidator`. Since the bug is a pretty annoying one, I'll do a patch release off the `0.17.3` tag over there.

**Comment by areqq** [comment]
now it works great ! Thank a lot for ultra fast and excellent support !

```
./.local/bin/pyhanko sign validate --pretty-print  --trust nccert2016.crt --no-diff-analysis  PDF_sign_test.pdf
=========================
Field 1: InitializingSeal
=========================


Signer info
-----------
Certificate subject: "Common Name: Autenti Sp. z o.o.; Organization: Autenti Sp. z o.o.; Country: PL; Organization Identifier: VATPL-7831693251; 2.5.4.16: OrderedDict([('0', 'Święty Marcin 29/8'), ('1', '61-806 Poznań'), ('2', 'wielkopolskie')])"
Certificate SHA1 fingerprint: 907f61a04d83d72f8467d19b24330eefbdfb75a9
Certificate SHA256 fingerprint: 46f51402b608c5a65d05e501f5a5492be42f698b731e0f7c4e90a4d83f4e11d2
Trust anchor: "Organization Identifier: VATPL-5250008198, Common Name: Narodowe Centrum Certyfikacji, Organization: Narodowy Bank Polski, Country: PL"
The signer's certificate is trusted.


Integrity
---------
The signature is cryptographically sound.

The digest algorithm used was 'sha256'.
The signature mechanism used was 'rsassa_pkcs1v15'.


Signing time
------------
Signing time as reported by signer: 2021-11-13T20:12:20+01:00

Signature timestamp token: 2021-11-13T19:12:21+00:00
The token is guaranteed to be newer than the signature.
This timestamp is backed by a time stamping authority.
The timestamp token is cryptographically sound.
TSA certificate subject: "Organization Identifier: VATPL-5170359458, Common Name: Certum QTST 2017, Organization: Asseco Data Systems S.A., Country: PL"
TSA certificate SHA1 fingerprint: 6e23cdb967f06d3fda85316c5b47361cd55542ac
TSA certificate SHA256 fingerprint: 673be8a1da927db63ccab7cb3e7ac352dc3aeb6a8da3e2a359ca158d0a440db8
TSA cert trust anchor: "Organization Identifier: VATPL-5250008198, Common Name: Narodowe Centrum Certyfikacji, Organization: Narodowy Bank Polski, Country: PL"
The TSA certificate is trusted.

Content timestamp token: 2021-11-13T19:12:21+00:00
The token is guaranteed to be older than the signature.
This timestamp is backed by a time stamping authority.
The timestamp token is cryptographically sound.
TSA certificate subject: "Organization Identifier: VATPL-5170359458, Common Name: Certum QTST 2017, Organization: Asseco Data Systems S.A., Country: PL"
TSA certificate SHA1 fingerprint: 6e23cdb967f06d3fda85316c5b47361cd55542ac
TSA certificate SHA256 fingerprint: 673be8a1da927db63ccab7cb3e7ac352dc3aeb6a8da3e2a359ca158d0a440db8
TSA cert trust anchor: "Organization Identifier: VATPL-5250008198, Common Name: Narodowe Centrum Certyfikacji, Organization: Narodowy Bank Polski, Country: PL"
The TSA certificate is trusted.


Modifications
-------------
Incremental update analysis was skipped


Bottom line
-----------
The signature is judged VALID.


===================
Field 2: Signature1
===================


Signer info
-----------
Certificate subject: "Common Name: Autenti Sp. z o.o.; Organization: Autenti Sp. z o.o.; Country: PL; Organization Identifier: VATPL-7831693251; 2.5.4.16: OrderedDict([('0', 'Święty Marcin 29/8'), ('1', '61-806 Poznań'), ('2', 'wielkopolskie')])"
Certificate SHA1 fingerprint: 907f61a04d83d72f8467d19b24330eefbdfb75a9
Certificate SHA256 fingerprint: 46f51402b608c5a65d05e501f5a5492be42f698b731e0f7c4e90a4d83f4e11d2
Trust anchor: "Organization Identifier: VATPL-5250008198, Common Name: Narodowe Centrum Certyfikacji, Organization: Narodowy Bank Polski, Country: PL"
The signer's certificate is trusted.


Integrity
---------
The signature is cryptographically sound.

The digest algorithm used was 'sha256'.
The signature mechanism used was 'rsassa_pkcs1v15'.


Signing time
------------
Signing time as reported by signer: 2021-11-13T20:12:29+01:00

Signature timestamp token: 2021-11-13T19:12:30+00:00
The token is guaranteed to be newer than the signature.
This timestamp is backed by a time stamping authority.
The timestamp token is cryptographically sound.
TSA certificate subject: "Organization Identifier: VATPL-5170359458, Common Name: Certum QTST 2017, Organization: Asseco Data Systems S.A., Country: PL"
TSA certificate SHA1 fingerprint: 6e23cdb967f06d3fda85316c5b47361cd55542ac
TSA certificate SHA256 fingerprint: 673be8a1da927db63ccab7cb3e7ac352dc3aeb6a8da3e2a359ca158d0a440db8
TSA cert trust anchor: "Organization Identifier: VATPL-5250008198, Common Name: Narodowe Centrum Certyfikacji, Organization: Narodowy Bank Polski, Country: PL"
The TSA certificate is trusted.

Content timestamp token: 2021-11-13T19:12:30+00:00
The token is guaranteed to be older than the signature.
This timestamp is backed by a time stamping authority.
The timestamp token is cryptographically sound.
TSA certificate subject: "Organization Identifier: VATPL-5170359458, Common Name: Certum QTST 2017, Organization: Asseco Data Systems S.A., Country: PL"
TSA certificate SHA1 fingerprint: 6e23cdb967f06d3fda85316c5b47361cd55542ac
TSA certificate SHA256 fingerprint: 673be8a1da927db63ccab7cb3e7ac352dc3aeb6a8da3e2a359ca158d0a440db8
TSA cert trust anchor: "Organization Identifier: VATPL-5250008198, Common Name: Narodowe Centrum Certyfikacji, Organization: Narodowy Bank Polski, Country: PL"
The TSA certificate is trusted.


Modifications
-------------
Incremental update analysis was skipped


Bottom line
-----------
The signature is judged VALID.


=======================
Field 3: FinalizingSeal
=======================


Signer info
-----------
Certificate subject: "Common Name: Autenti Sp. z o.o.; Organization: Autenti Sp. z o.o.; Country: PL; Organization Identifier: VATPL-7831693251; 2.5.4.16: OrderedDict([('0', 'Święty Marcin 29/8'), ('1', '61-806 Poznań'), ('2', 'wielkopolskie')])"
Certificate SHA1 fingerprint: 907f61a04d83d72f8467d19b24330eefbdfb75a9
Certificate SHA256 fingerprint: 46f51402b608c5a65d05e501f5a5492be42f698b731e0f7c4e90a4d83f4e11d2
Trust anchor: "Organization Identifier: VATPL-5250008198, Common Name: Narodowe Centrum Certyfikacji, Organization: Narodowy Bank Polski, Country: PL"
The signer's certificate is trusted.


Integrity
---------
The signature is cryptographically sound.

The digest algorithm used was 'sha256'.
The signature mechanism used was 'rsassa_pkcs1v15'.


Signing time
------------
Signing time as reported by signer: 2021-11-13T20:12:32+01:00

Signature timestamp token: 2021-11-13T19:12:33+00:00
The token is guaranteed to be newer than the signature.
This timestamp is backed by a time stamping authority.
The timestamp token is cryptographically sound.
TSA certificate subject: "Organization Identifier: VATPL-5170359458, Common Name: Certum QTST 2017, Organization: Asseco Data Systems S.A., Country: PL"
TSA certificate SHA1 fingerprint: 6e23cdb967f06d3fda85316c5b47361cd55542ac
TSA certificate SHA256 fingerprint: 673be8a1da927db63ccab7cb3e7ac352dc3aeb6a8da3e2a359ca158d0a440db8
TSA cert trust anchor: "Organization Identifier: VATPL-5250008198, Common Name: Narodowe Centrum Certyfikacji, Organization: Narodowy Bank Polski, Country: PL"
The TSA certificate is trusted.

Content timestamp token: 2021-11-13T19:12:33+00:00
The token is guaranteed to be older than the signature.
This timestamp is backed by a time stamping authority.
The timestamp token is cryptographically sound.
TSA certificate subject: "Organization Identifier: VATPL-5170359458, Common Name: Certum QTST 2017, Organization: Asseco Data Systems S.A., Country: PL"
TSA certificate SHA1 fingerprint: 6e23cdb967f06d3fda85316c5b47361cd55542ac
TSA certificate SHA256 fingerprint: 673be8a1da927db63ccab7cb3e7ac352dc3aeb6a8da3e2a359ca158d0a440db8
TSA cert trust anchor: "Organization Identifier: VATPL-5250008198, Common Name: Narodowe Centrum Certyfikacji, Organization: Narodowy Bank Polski, Country: PL"
The TSA certificate is trusted.


Modifications
-------------
Incremental update analysis was skipped


Bottom line
-----------
The signature is judged VALID.
```

**Comment by MatthiasValvekens** [comment]
Happy to help :).

Working with alpha software is a double-edged sword: there are occasional bugs, but I can also still afford to do patch releases on very short notice ;).

I'll close this now, thanks for the report! If you run into any other trouble, feel free to open a new issue.

**Comment by areqq** [comment]
for cmd I use --trust nccert2016.crt, how to get this in python code ?

with:
```
root_cert = load_cert_from_pemder('nccert2016.crt')
vc = ValidationContext( other_certs = [root_cert], allow_fetching=True)

with open('pdf.pdf', 'rb') as doc:
    r = PdfFileReader(doc)
    sig = r.embedded_signatures[0]
    status = validate_pdf_signature(sig, vc, skip_diff=True)
```

I got:
```Unable to build a validation path for the certificate "Organization Identifier: VATPL-5170359458, Common Name: Certum QTST 2017, Organization: Asseco Data Systems S.A., Country: PL" - no issuer matching "Organization Identifier: VATPL-5250008198, Common Name: Narodowe Centrum Certyfikacji, Organization: Narodowy Bank Polski, Country: PL" was found
Chain of trust validation for Organization Identifier: VATPL-5170359458, Common Name: Certum QTST 2017, Organization: Asseco Data Systems S.A., Country: PL failed.
Unable to build a validation path for the certificate "Common Name: Autenti Sp. z o.o.; Organization: Autenti Sp. z o.o.; Country: PL; Organization Identifier: VATPL-7831693251; 2.5.4.16: OrderedDict([('0', 'Święty Marcin 29/8'), ('1', '61-806 Poznań'), ('2', 'wielkopolskie')])" - no issuer matching "Organization Identifier: VATPL-5260300517, Common Name: COPE SZAFIR - Kwalifikowany, Organization: Krajowa Izba Rozliczeniowa S.A., Country: PL" was found
Chain of trust validation for Common Name: Autenti Sp. z o.o.; Organization: Autenti Sp. z o.o.; Country: PL; Organization Identifier: VATPL-7831693251; 2.5.4.16: OrderedDict([('0', 'Święty Marcin 29/8'), ('1', '61-806 Poznań'), ('2', 'wielkopolskie')]) failed.
Signer info
-----------
Certificate subject: "Common Name: Autenti Sp. z o.o.; Organization: Autenti Sp. z o.o.; Country: PL; Organization Identifier: VATPL-7831693251; 2.5.4.16: OrderedDict([('0', 'Święty Marcin 29/8'), ('1', '61-806 Poznań'), ('2', 'wielkopolskie')])"
Certificate SHA1 fingerprint: 907f61a04d83d72f8467d19b24330eefbdfb75a9
Certificate SHA256 fingerprint: 46f51402b608c5a65d05e501f5a5492be42f698b731e0f7c4e90a4d83f4e11d2
Trust anchor: "No path to trust anchor found."
The signer's certificate is untrusted.```

**Comment by MatthiasValvekens** [comment]
Hi there,

You'll need to put the trust root in the `trust_roots` or `extra_trust_roots` parameters to `ValidationContext`; `other_certs` is for (a priori) untrusted certificates that the path building logic needs to know about, e.g. intermediate CAs and the like.

Whether you need to use `trust_roots` or `extra_trust_roots` depends on your use case: if you want to include all trust roots on the system trust list (as reported by `oscrypto`), then `extra_trust_roots` is the way to go. If you specifically want to rely only on one trust root, then use the `trust_roots` parameter.

Does that help?

------

While I have your attention, I'd also like to point out that we have a discussion forum now for this kind of support-type questions: https://github.com/MatthiasValvekens/pyHanko/discussions :)

**Comment by areqq** [comment]
with extra_trust_roots works, thanks again
and next time I will use discussions ;)
