### ISSUE TITLE
Parse error in fetched certificate propagates to CLI

### ISSUE THREAD

**Issue by ghoshpushpendu** [MatthiasValvekens/pyHanko#63]
`pyhanko sign addsig --field signature1 --with-validation-info --use-pades pkcs12 output.pdf signed.pdf  emudhra.pfx --passfile password.txt`

this above is the whole command.

which produces the following error.

`2021-12-04 18:54:37,804 - pyhanko.cli - ERROR - Generic processing error.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyhanko_certvalidator/fetchers/common_utils.py", line 145, in queue_fetch_task
    wait_event: asyncio.Event = running_jobs[tag]
KeyError: 'http://www.e-mudhra.com/repository/cacerts/doccl2.crt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyhanko/cli.py", line 80, in pyhanko_exception_manager
    yield
  File "/usr/local/lib/python3.9/site-packages/pyhanko/cli.py", line 831, in addsig_simple_signer
    generic_sign_pdf(
  File "/usr/local/lib/python3.9/site-packages/pyhanko/cli.py", line 841, in generic_sign_pdf
    result = signers.PdfSigner(
  File "/usr/local/lib/python3.9/site-packages/pyhanko/sign/signers/pdf_signer.py", line 1220, in sign_pdf
    result = asyncio.run(
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/pyhanko/sign/signers/pdf_signer.py", line 1272, in async_sign_pdf
    await signing_session.perform_presign_validation(pdf_out)
  File "/usr/local/lib/python3.9/site-packages/pyhanko/sign/signers/pdf_signer.py", line 1419, in perform_presign_validation
    signer_path = await self._perform_presign_signer_validation(
  File "/usr/local/lib/python3.9/site-packages/pyhanko/sign/signers/pdf_signer.py", line 1476, in _perform_presign_signer_validation
    await validator.async_validate_usage(key_usage)
  File "/usr/local/lib/python3.9/site-packages/pyhanko_certvalidator/__init__.py", line 283, in async_validate_usage
    await self._validate_path()
  File "/usr/local/lib/python3.9/site-packages/pyhanko_certvalidator/__init__.py", line 127, in _validate_path
    paths = await self._context.certificate_registry.async_build_paths(
  File "/usr/local/lib/python3.9/site-packages/pyhanko_certvalidator/registry.py", line 425, in async_build_paths
    await self._walk_issuers(path, paths, failed_paths)
  File "/usr/local/lib/python3.9/site-packages/pyhanko_certvalidator/registry.py", line 477, in _walk_issuers
    async for issuer in self.fetcher.fetch_cert_issuers(path.first):
  File "/usr/local/lib/python3.9/site-packages/pyhanko_certvalidator/fetchers/requests_fetchers/cert_fetch_client.py", line 69, in fetch_cert_issuers
    fetched_certs = await self.fetch_certs(
  File "/usr/local/lib/python3.9/site-packages/pyhanko_certvalidator/fetchers/requests_fetchers/cert_fetch_client.py", line 56, in fetch_certs
    return await self._perform_fetch(url, task)
  File "/usr/local/lib/python3.9/site-packages/pyhanko_certvalidator/fetchers/requests_fetchers/util.py", line 37, in _perform_fetch
    return await queue_fetch_task(
  File "/usr/local/lib/python3.9/site-packages/pyhanko_certvalidator/fetchers/common_utils.py", line 176, in queue_fetch_task
    return _return_or_raise(result)
  File "/usr/local/lib/python3.9/site-packages/pyhanko_certvalidator/fetchers/common_utils.py", line 181, in _return_or_raise
    raise result
  File "/usr/local/lib/python3.9/site-packages/pyhanko_certvalidator/fetchers/common_utils.py", line 163, in queue_fetch_task
    result = await async_fun()
  File "/usr/local/lib/python3.9/site-packages/pyhanko_certvalidator/fetchers/requests_fetchers/cert_fetch_client.py", line 55, in task
    return list(results)
  File "/usr/local/lib/python3.9/site-packages/pyhanko_certvalidator/fetchers/common_utils.py", line 38, in unpack_cert_content
    yield x509.Certificate.load(response_data)
  File "/usr/local/lib/python3.9/site-packages/asn1crypto/core.py", line 230, in load
    value, _ = _parse_build(encoded_data, spec=spec, spec_params=kwargs, strict=strict)
  File "/usr/local/lib/python3.9/site-packages/asn1crypto/core.py", line 5672, in _parse_build
    return (_build(*info, spec=spec, spec_params=spec_params), new_pointer)
  File "/usr/local/lib/python3.9/site-packages/asn1crypto/core.py", line 5568, in _build
    raise ValueError(unwrap(
ValueError: Error parsing asn1crypto.x509.Certificate - tag should have been 16, but 13 was found
Error: Generic processing error.`

**Comment by MatthiasValvekens** [comment]
Hi @ghoshpushpendu, thanks for your interest in this project!

The issue is that the server hosting `http://www.e-mudhra.com/repository/cacerts/doccl2.crt` serves a PEM-wrapped certificate instead of a DER-encoded one, and announces it as `application/x-x509-ca-cert`. This is wrong for two reasons:

 - Certificate links in an AIA extension _must_ point to DER-encoded certificates.
 - The MIME definition of `application/x-x509-ca-cert` also requires raw DER.

`pyhanko-certvalidator` is currently lenient w.r.t. the first requirement in that it also accepts PEM _if_ the `Content-Type` header is `text/plain` or `application/x-pem-file`, but if the server gets both the encoding and the MIME type wrong, then you get a parse error. That's mostly intentional, but the fact that the parse error propagates to the CLI is a bug indeed. I'll look into addressing that.

In the meantime, you can manually download the certificate at `http://www.e-mudhra.com/repository/cacerts/doccl2.crt` and pass in the file using the `--other-certs` flag (or add it to `other-certs` in your validation context in the config file). From a validation logic point of view, those are equivalent.

Hope that helps :)

**Comment by MatthiasValvekens** [comment]
I did a bugfix release of `pyhanko-certvalidator` (version `0.18.1`) that should fix this bug---see linked commit. Note that I didn't change the parse logic to accept PEM certificates with wrong MIME types; the fix merely ensures that parse errors resulting from such mishaps don't propagate outside of the validation handler.

In other words, you'll now get a regular `PathBuildingError` instead of a `ValueError`. In either case, the problem can be remedied by manually downloading the certificate and adding it as an untrusted certificate (`--other-certs`) to your validation context, as per my previous comment.

For further information, see

 - https://pyhanko.readthedocs.io/en/latest/cli-guide/signing.html#embedding-revocation-info-with-pyhanko (third paragraph)
 - https://pyhanko.readthedocs.io/en/latest/cli-guide/config.html#named-validation-contexts (if you want to configure the extra certificates in the config file)

Hope that helps; if not, feel free to reopen. :)

**Comment by ghoshpushpendu** [comment]
> Hi @ghoshpushpendu, thanks for your interest in this project!
> 
> The issue is that the server hosting `http://www.e-mudhra.com/repository/cacerts/doccl2.crt` serves a PEM-wrapped certificate instead of a DER-encoded one, and announces it as `application/x-x509-ca-cert`. This is wrong for two reasons:
> 
> * Certificate links in an AIA extension _must_ point to DER-encoded certificates.
> * The MIME definition of `application/x-x509-ca-cert` also requires raw DER.
> 
> `pyhanko-certvalidator` is currently lenient w.r.t. the first requirement in that it also accepts PEM _if_ the `Content-Type` header is `text/plain` or `application/x-pem-file`, but if the server gets both the encoding and the MIME type wrong, then you get a parse error. That's mostly intentional, but the fact that the parse error propagates to the CLI is a bug indeed. I'll look into addressing that.
> 
> In the meantime, you can manually download the certificate at `http://www.e-mudhra.com/repository/cacerts/doccl2.crt` and pass in the file using the `--other-certs` flag (or add it to `other-certs` in your validation context in the config file). From a validation logic point of view, those are equivalent.
> 
> Hope that helps :)

this resolves the error and successfully generates the certificate 
but the purpose of using "--with-validation-info" is not getting fulfilled as the PDF is not automatically validate it when opened.

**Comment by ghoshpushpendu** [comment]
`validation-contexts:
    default:
        other-certs: other.txt
    special-setup:
        trust: trust.txt
        trust-replace: true
        other-certs: other.txt`

**Comment by ghoshpushpendu** [comment]
pyhanko sign addfields --field  1/1,1,100,100/signature1 sample.pdf output.pdf

pyhanko sign addsig --field signature1 --with-validation-info --validation-context special-setup pkcs12 output.pdf signed.pdf  emudhra.pfx --passfile password.txt

**Comment by ghoshpushpendu** [comment]
`pyhanko sign addsig --field signature1 --style-name mystyle --with-validation-info --validation-context special-setup --use-pades pkcs12 output.pdf signed.pdf  emudhra.pfx --passfile password.txt`

fixes the issue

**Comment by MatthiasValvekens** [comment]
>  but the purpose of using "--with-validation-info" is not getting fulfilled as the PDF is not automatically validate it when opened.

I'm not sure what you mean by this; `--with-validation-info` is only about including prefetched revocation data. A viewers decision as to _when_ it validates a signature has little to do with that, and isn't something you can reliably control as a signer...

But maybe I misunderstood your point. Anyway, if your issue is resolved now, then I suppose it doesn't matter :)

**Comment by ghoshpushpendu** [comment]
> > but the purpose of using "--with-validation-info" is not getting fulfilled as the PDF is not automatically validate it when opened.
> 
> I'm not sure what you mean by this; `--with-validation-info` is only about including prefetched revocation data. A viewers decision as to _when_ it validates a signature has little to do with that, and isn't something you can reliably control as a signer...
> 
> But maybe I misunderstood your point. Anyway, if your issue is resolved now, then I suppose it doesn't matter :)

When signing PDF using a valid certificate , I was not able to run revocation check every time viewer opens the PDF.

So the PDF was showing as `at least one signature has an issue`

I am also not sure but `--use-pades` does the job. 

After adding `--use-pades` it shows signed every time I open the PDF from anywhere without any extra action as a viewer.

**Comment by MatthiasValvekens** [comment]
That's interesting. For reference: which PDF viewer are you using?

The difference between adding `--use-pades` and not using it is where the revocation information is stored. Without the `--use-pades` flag, pyHanko will put that information in the `revInfoArchival` attribute of the signature. With `--use-pades` it gets written to the document security store.

**Comment by ghoshpushpendu** [comment]
Adobe Acrobat Reader DC
