### ISSUE TITLE
Signing an already signed document changes /MediaBox type from pyhanko.pdf_utils.generic.NumberObject to pyhanko.pdf_utils.generic.FloatObject

### ISSUE THREAD

**Issue by gchehab** [MatthiasValvekens/pyHanko#7]
**Describe the bug**
Signing a already signed PAdES pdf file seems to change the /MediaBox coordinates types from NumberObject to FloatObject, leading to a invalid first signature.

**To Reproduce**

1. Using a pdf file signed with external PAdES signer, sign it with pyhanko:
`python -m pyhanko sign addsign --use-pades --field 1/0,0,240,40/SignatureSinc pemder --cert testdata/cert/cert.pem --key testdata/cert/key.pem testdata/test1.pdf testdata/test2.pdf`
2. Validate signed file
`python -m pyhanko sign validate --pretty-print testdata/test2.pdf`
Gives this error:
```
021-03-09 14:40:38,205 - pyhanko.sign.diff_analysis - WARNING - Error in diff operation between revision 1 and 2
Traceback (most recent call last):
  File "c:\users\guilhermec\source\repos\assinador\validador\env\src\pyhanko\pyhanko\sign\diff_analysis.py", line 2067, in review_file
    diff_result = self.apply(
  File "c:\users\guilhermec\source\repos\assinador\validador\env\src\pyhanko\pyhanko\sign\diff_analysis.py", line 1967, in apply
    for level, fu in form_changes:
  File "c:\users\guilhermec\source\repos\assinador\validador\env\src\pyhanko\pyhanko\sign\diff_analysis.py", line 1211, in apply
    yield from rule.apply(context)
  File "c:\users\guilhermec\source\repos\assinador\validador\env\src\pyhanko\pyhanko\sign\diff_analysis.py", line 826, in apply
    yield from qualify(
  File "c:\users\guilhermec\source\repos\assinador\validador\env\src\pyhanko\pyhanko\pdf_utils\misc.py", line 218, in map_with_return
    yield func(next(gen))
  File "c:\users\guilhermec\source\repos\assinador\validador\env\src\pyhanko\pyhanko\sign\diff_analysis.py", line 1644, in _walk_page_tree_annots
    _compare_dicts(old_kid, new_kid, {'/Annots'})
  File "c:\users\guilhermec\source\repos\assinador\validador\env\src\pyhanko\pyhanko\sign\diff_analysis.py", line 1717, in _compare_dicts
    raise SuspiciousModification(
pyhanko.sign.diff_analysis.SuspiciousModification: Values for dict key /MediaBox differ:[0, 0, 841.92, 595.32] changed to [0, 0, 841.92, 595.32]
```
And complains about integrity:
```
Integrity
---------
The signature is cryptographically sound.
The signature does not cover the entire file.
Some modifications may be illegitimate, and they appear to be incompatible with the current document modification policy.
```
The MediaBox comparison,  using DeepDiff module,  had dectected the following diferences:
```
{'type_changes': {'root[0]': {'new_type': <class 'pyhanko.pdf_utils.generic.FloatObject'>,
                              'new_value': 0,
                              'old_type': <class 'pyhanko.pdf_utils.generic.NumberObject'>,
                              'old_value': 0},
                  'root[1]': {'new_type': <class 'pyhanko.pdf_utils.generic.FloatObject'>,
                              'new_value': 0,
                              'old_type': <class 'pyhanko.pdf_utils.generic.NumberObject'>,
                              'old_value': 0}},
 'values_changed': {'root[2]': {'new_value': 841.92, 'old_value': 841.92},
                    'root[3]': {'new_value': 595.32, 'old_value': 595.32}}}

```
**Expected behavior**
It should validate the integrity of both signatures:

**Screenshots**
n/a

**Environment (please complete the following information):**
 - OS: Windows 10
 - Version 5.0 dev1

**Additional context**
I am studying adapt pyhanko to validate and sign according with Brazilian standard signed PAdES documents (/SubFilter PBAD-PAdES), that is mostly compatible with ETSI PAdES with minor changes.

**Comment by MatthiasValvekens** [comment]
Thanks for the detailed bug report! Odds are that the problem has to do with comparison routines not dealing with mixed-type comparisons properly; I'll look into that. Just for good measure: can you share the signed file?

**Comment by gchehab** [comment]
> Thanks for the detailed bug report! Odds are that the problem has to do with comparison routines not dealing with mixed-type comparisons properly; I'll look into that. Just for good measure: can you share the signed file?

The strangest thing is that the digest seems to validate. I suppose that the signature encompass the original MediaBox property, so the problem might be on the type casting of parser of the old or the new coordinates, or, eventually, in the new pdf file saving. 

Being more permissive on the mixed-type comparisons should work, but I wonder if it could create other issues or weaken the validation.

I am attaching sample pdf files (unsigned, one signature -- externally signed with a Brazilian valid CA --, and two signatures -- the second using pyhanko and self-signed  pem certs) using PBAD-PAdES, that is the same standard I used for the tests. I will try to test with the standard ETSI-PADES, however, I do not think that this is source of the issue.

In the fork I am working on there are the changes needed to validate this kind of file [changes from original project](https://github.com/MatthiasValvekens/pyHanko/compare/master...gchehab:master)

So far just minor changes needed, actually just adding the `/SubFilter PBAD-PAdES` does the trick -- I have also added an option to not ask passphrase to the pemder to make my tests easier, in production I'll use a passphrase file as I should.

 
[test-signed_2.pdf](https://github.com/MatthiasValvekens/pyHanko/files/6111092/test-signed_2.pdf)
[test.pdf](https://github.com/MatthiasValvekens/pyHanko/files/6111094/test.pdf)
[test-signed_1.pdf](https://github.com/MatthiasValvekens/pyHanko/files/6111095/test-signed_1.pdf)

**Comment by MatthiasValvekens** [comment]
Thanks for sharing! From a quick inspection of your files, it seems that the issue is that pyHanko reserialises the page object with a different  precision. The underlying reason for that is that it uses `%g` to serialise `FloatObject` values, which apparently cuts off its input at 10^-4 (the original width / height of the page is actually 595.32001 x 841.92004). This is (partially) a holdover from PyPDF2.

Internally, pyHanko still uses `Decimal` objects, so the part of the validation logic that vets updates to signed files complains that the values don't match.


Could you try changing the last line in the `__repr__ ` implementation for `FloatObject` to `return str(self)` and recreate the signature? I think that should resolve your issue. If it does, I'll commit it with some tests.

**Comment by MatthiasValvekens** [comment]
Sure, I'd certainly be happy to consider a pull request when you're done. I admittedly didn't give much thought to supporting SubFilter values that aren't listed in the (PDF) standard, though, so perhaps it makes sense to rearrange a few things to make that easier going forward. That shouldn't involve too much work, though. :)
